const GenreEnum = Object.freeze({
    ACT: 'Action',
    ADV: 'Adventure',
    CAR: 'Cars',
    COM: 'Comedy',
    DEM: 'Dementia',
    DEO: 'Demons',
    DRA: 'Drama',
    HAR: 'Harem',
    HIS: 'Historical',
    HOR: 'Horror',
    JOS: 'Josei',
    KID: 'Kids',
    MAG: 'Magic',
    MAA: 'Martial Arts',
    MEC: 'Mecha',
    MIL: 'Military',
    MUS: 'Music',
    MYS: 'Mystery',
    PAR: 'Parody',
    POL: 'Police',
    PSY: 'Psychological',
    ROM: 'Romance',
    SAM: 'Samurai',
    SCH: 'School',
    SCI: 'Sci-Fi',
    SEI: 'Seinen',
    SHJ: 'Shoujo',
    SHN: 'Shounen',
    SOL: 'Slice Of Life',
    SPC: 'Space',
    SPO: 'Sport',
    SPN: 'Supernatural',
    SPP: 'Superpower',
    THR: 'Thriller',
    VAM: 'Vampire'
})

// Split / Convert this

// GenreList = [
//     'ACT',
//     'ADV',
//     'CAR',
//     'COM',
//     'DEM',
//     'DEO',
//     'DRA',
//     'HAR',
//     'HIS',
//     'HOR',
//     'JOS',
//     'KID',
//     'MAG',
//     'MAA',
//     'MEC',
//     'MIL',
//     'MUS',
//     'MYS',
//     'PAR',
//     'POL',
//     'PSY',
//     'ROM',
//     'SAM',
//     'SCH',
//     'SCI',
//     'SEI',
//     'SHJ',
//     'SHN',
//     'SOL',
//     'SPC',
//     'SPO',
//     'SPN',
//     'SPP',
//     'THR',
//     'VAM',
// ]

export default GenreEnum 